### ISSUE TITLE
handler breaks zerolog.ConsoleWriter

### ISSUE THREAD

**Issue by ghost** [yfuruyama/crzerolog#3]
hi,

for local development, we setup the zerolog logger with a ConsoleWriter.

However, since the crzerolog handler is removing the "level" field, replacing? it with "severity", the console writer cannot see the log level producing output such as
```
1:51PM ??? call the starters count=0
1:51PM ??? services are ready for business
```

**Comment by ghost** [comment]
maybe the Console write should respect `zerolog.LevelFieldName`

**Comment by ghost** [comment]
my workaround is to override the FormalLevel as the crzerolog pkg changes the labels for the levels.
```
cons := zerolog.ConsoleWriter{Out: os.Stderr}
cons.FormatLevel = func(i interface{}) string {
	if s, ok := i.(string); ok {
		return s
	}
	return "<?>"
}
```

**Comment by yfuruyama** [comment]
Thanks @ernest-ag5. This package [renames](https://github.com/yfuruyama/crzerolog/blob/9552417214f4d6b2360ae432acb824bbcbce4176/log.go#L32-L55) the level value and that causes `???` in zerolog ConsoleWriter [logic](https://github.com/rs/zerolog/blob/e218d18951a18f1ef4bd3384f95b7e58abd9c90b/console.go#L388).

I filed a PR in zerolog to fix this issue: https://github.com/rs/zerolog/pull/476

For the time being, please use the workaround you mentioned.

**Comment by yfuruyama** [comment]
This issue was fixed in https://github.com/yfuruyama/crzerolog/pull/4, please use the latest version of this package.

**Comment by ghost** [comment]
please create a new tag so I can update my deps

**Comment by yfuruyama** [comment]
@ernest-ag5 Tagged: https://github.com/yfuruyama/crzerolog/releases/tag/v0.3.1

Thanks!
